# Generated by Django 5.2.7 on 2025-11-10 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demonym", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["demonym"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ref", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(blank=True, max_length=6)),
                ("forename", models.CharField(blank=True, max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.nationality",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
