# Generated by Django 5.2.7 on 2025-11-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_nationality_and_drivers"),
    ]

    operations = []
