# Generated by Django 5.2.7 on 2025-11-10 22:47
import pandas

from django.db import migrations


CSV_DATA_PATH: str = "/app/data_csv/"


def insert_nationality(apps, _):
    with open(
            file=f"{CSV_DATA_PATH}demonyms-nationality.csv",
            mode="r",
            encoding="utf-8",
    ) as csv_file:
        column_headers = ["demonym", "country"]
        f= pandas.read_csv(csv_file, header=0, usecols=column_headers)

        # objects we are working with
        Nationality = apps.get_model(app_label="app", model_name="nationality")

        # bulk create
        n_objs = [Nationality(demonym=d, country=c) for d, c in f.to_numpy()]
        Nationality.objects.bulk_create(objs=n_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_nationality_and_drivers"),
    ]

    operations = [
        migrations.RunPython(
            code=insert_nationality,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
    ]
