# Generated by Django 5.2.7 on 2025-11-11 00:34
import pandas

from django.db import migrations


def insert_drivers(apps, _):
    with open(
        file="/app/data_csv/f1/drivers.csv",
        mode="r",
        encoding="utf-8",
    ) as csv_file:
        column_headers = [
            "driverId",
            "driverRef",
            "number",
            "code",
            "forename",
            "surname",
            "dob",
            "nationality",
            "url",
        ]
        f = pandas.read_csv(csv_file, header=0, usecols=column_headers)

        # the objects we're working with (creation in this instance)
        Nationality = apps.get_model(app_label="app", model_name="Nationality")
        Driver = apps.get_model(app_label="app", model_name="Driver")

        # bulk create
        d_objs = []
        for d_id, r, num, c, f, l, d, n, u in f.to_numpy():
            d_objs.append(Driver(
                id=d_id,
                ref=r.lower(),
                number=num if num.isdigit() else "",
                code=c if c.isalnum() else "",
                forename=f,
                surname=l,
                date_of_birth=d,
                nationality=Nationality.objects.filter(demonym=n).first(),
                url=u,
            ))
        Driver.objects.bulk_create(objs=d_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_insert_nationality"),
    ]

    operations = [
        migrations.RunPython(
            code=insert_drivers,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
    ]
