# Generated by Django 5.2.7 on 2025-11-13 19:18
import pandas

import django.db.models.deletion
from django.db import migrations, models


def insert_circuits(apps, schema_editor):
    with open(file="/app/data_csv/f1/circuits.csv",
                    mode="r",
                    encoding="utf-8") as input_file:
        column_headers = ["circuitId",
                                       "circuitRef",
                                       "name",
                                       "location",
                                       "country",
                                       "lat",
                                       "lng",
                                       "alt",
                                       "url"]
        csv_file = pandas.read_csv(input_file, usecols=column_headers)

        Nationality = apps.get_model("app", "Nationality")
        Circuit = apps.get_model("app", "Circuit")

        c_objs = []
        for c_id, r, n, l, c, y, x, a, u in csv_file.to_numpy():
            c_objs.append(Circuit(id=c_id,
                                               ref=r,
                                               name=n,
                                               location=l,
                                               country=Nationality.objects.filter(country=c).first(),
                                               longitude=x,
                                               latitude=y,
                                               altitude=a,
                                               url=u))
        Circuit.objects.bulk_create(c_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_insert_drivers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuit",
            options={"ordering": ["id"]},
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("longitude",models.DecimalField(blank=True, decimal_places=16, max_digits=32)),
                ("latitude", models.DecimalField(blank=True, decimal_places=16, max_digits=32)),
                ("altitude", models.IntegerField(blank=True, help_text="Measured in meters")),
                ("url", models.URLField(blank=True)),
                ("country", models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to="app.nationality")),
            ],
        ),
        migrations.RunPython(insert_circuits, migrations.RunPython.noop, True),
    ]
