# Generated by Django 5.2.7 on 2025-11-13 20:06

from django.db import migrations, models
from django.utils import timezone


def mark_deleted_at(apps, _):
    Nationality = apps.get_model("app", "Nationality")
    nationality_objs = Nationality.objects.all()
    for n in nationality_objs:
        n.deleted_at = timezone.now()
    Nationality.objects.bulk_update(nationality_objs, ["deleted_at"])


def create_distinct_countries(apps, _):
    Nationality = apps.get_model("app", "Nationality")
    nationality_set = Nationality.objects.order_by("country").distinct("country")

    # Create new unique values so that we never actually delete
    Nationality.objects.bulk_create([Nationality(demonym=i.demonym, country=i.country) for i in nationality_set])


class Migration(migrations.Migration):

    dependencies = [("app", "0004_circuit")]

    operations = [
        migrations.AddField(
            model_name="Nationality",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            mark_deleted_at,
            migrations.RunPython.noop,
            True,
        ),
        migrations.RunPython(
            create_distinct_countries,
            migrations.RunPython.noop,
            True,
        ),
    ]
