# Generated by Django 5.2.7 on 2025-11-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_normalize_nation"),
    ]

    operations = []
