# Generated by Django 5.2.7 on 2025-12-02 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_reassign_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            options={"ordering": ["-date_of_race"]},
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("date_of_race", models.DateField()),
                ("season_round_number", models.SmallIntegerField()),
                ("url", models.URLField(blank=True)),
                ("track", models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to="app.nationality")),
            ],
        ),
    ]

