# Generated by Django 5.2.7 on 2025-12-02 00:02
import pandas as pd
from datetime import datetime

import django.db.models.deletion
from django.db import migrations, models


def insert_race_data(apps, _):
    with open("/app/data_csv/f1/races.csv", "r", encoding="utf-8") as csv_file:
        column_headers = ["raceId", "round", "circuitId", "name", "date", "url"]
        df = pd.read_csv(csv_file, header=0, usecols=column_headers)

        Circuit = apps.get_model("app.Circuit")
        Race = apps.get_model("app.Race")

        # Create a map for lookup
        circuit_map = {c.id: c for c in Circuit.objects.only("id")}

        race_objs = []
        for r_id, r, c_id, n, d, u in df.to_numpy():
            date = datetime.strptime(d, "%Y-%m-%d")
            race_objs.append(Race(id=r_id,
                                                 name=n,
                                                 track=circuit_map[c_id],
                                                 date_of_race=date,
                                                 season_round_number=r,
                                                 url=u))
        Race.objects.bulk_create(race_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_reassign_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            options={"ordering": ["-date_of_race"]},
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("track", models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to="app.Circuit")),
                ("date_of_race", models.DateField()),
                ("season_round_number", models.SmallIntegerField()),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.RunPython(insert_race_data, migrations.RunPython.noop, True),
    ]

