# Generated by Django 5.2.7 on 2025-12-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_create_table_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="LapTime",
            options={"ordering": ["-race"]},
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("race", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name="lap_times", to="app.race")),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name="lap_times", to="app.driver")),
                ("lap_number", models.PositiveIntegerField()),
                ("time", models.DurationField(blank=True, null=True)),
                ("race_position", models.PositiveIntegerField()),
            ],
        ),
    ]
