# Generated by Django 5.2.7 on 2025-12-06 22:44
import pandas as pd
from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models
from utils.decorators import et


@et
def insert_laptimes(apps, _):
    with open("/app/data_csv/f1/lap_times.csv") as input_file:
        column_names = ["raceId", "driverId", "lap", "position", "milliseconds"]
        df = pd.read_csv(input_file, header=0, usecols=column_names)

        LapTime = apps.get_model("app", "LapTime")
        Race = apps.get_model("app", "Race")
        Driver = apps.get_model("app", "Driver")

        race_map = {i.id: i for i in Race.objects.only("id")}
        driver_map = {j.id: j for j in Driver.objects.only("id")}

        laptime_objs = []
        for r_id, d_id, l, p, t in df.to_numpy():
            lap_time = timedelta(milliseconds=int(t))
            laptime_objs.append(LapTime(
                race=race_map[r_id],
                driver=driver_map[d_id],
                lap_number=l,
                race_position=p,
                time=lap_time,
            ))
        LapTime.objects.bulk_create(laptime_objs)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_create_table_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="LapTime",
            options={"ordering": ["-race"]},
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("race", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name="lap_times", to="app.race")),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name="lap_times", to="app.driver")),
                ("lap_number", models.PositiveIntegerField()),
                ("time", models.DurationField(blank=True, null=True)),
                ("race_position", models.PositiveIntegerField()),
            ],
        ),
        migrations.RunPython(insert_laptimes, migrations.RunPython.noop, True),
    ]
